name: Semgrep SAST

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  permissions:
    contents: read

  jobs:
  semgrep:
    name: SAST - Semgrep
    runs-on: ubuntu-latest
    
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6  

      - name: Run Semgrep SAST
        run: semgrep scan --config auto